--DROP SEQUENCE SEQ_CHANGE_VENDOR_REQUEST;

-- Please set the correct ID value to use for the next insert
CREATE SEQUENCE "MKTG_CART_REQUEST_TOOL".SEQ_CHANGE_VENDOR_REQUEST START WITH 1 MINVALUE 0;
COMMIT;