CREATE COLUMN TABLE "MKTG_CART_REQUEST_TOOL"."CRM_CART_REQUEST_TOOL"
(
	 HL6_ID BIGINT CS_FIXED NOT NULL,
	 HL6_ID_CRM NVARCHAR(255) NOT NULL,
	 HL6_COST_CENTER NVARCHAR(255),
	 HL6_BUDGET_TOTAL DECIMAL(19,2),
	 HL6_STATUS NVARCHAR(255),
	 HL6_TEAM NVARCHAR(255),
	 HL6_ORIGIN NVARCHAR(255),
	 CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	 MODIFIED_DATE_TZ TIMESTAMP,
	 CREATED_USER_ID BIGINT NOT NULL,
	 MODIFIED_USER_ID BIGINT,
	 ENABLED TINYINT DEFAULT 1,
	 DELETED TINYINT DEFAULT 0,
	 PRIMARY KEY ("HL6_ID", "HL6_ID_CRM")
) 