CREATE COLUMN TABLE "MKTG_CART_REQUEST_TOOL"."CHANGE_VENDOR_SELECTION"
(
	CHANGE_VENDOR_REQUEST_ID BIGINT NOT NULL,
	SUPPORTING_DOCUMENTATION_ID BIGINT NOT NULL,
	SELECTION TINYINT NOT NULL DEFAULT 0,
	
	CREATED_USER_ID BIGINT NOT NULL,
	MODIFIED_USER_ID BIGINT,
	CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE_TZ TIMESTAMP,
	ENABLED TINYINT DEFAULT 1,
	DELETED TINYINT DEFAULT 0
);

ALTER TABLE "MKTG_CART_REQUEST_TOOL"."CHANGE_VENDOR_SELECTION" ADD FOREIGN KEY ( "CHANGE_VENDOR_REQUEST_ID" ) REFERENCES "MKTG_CART_REQUEST_TOOL"."CHANGE_VENDOR_REQUEST" ("CHANGE_VENDOR_REQUEST_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
ALTER TABLE "MKTG_CART_REQUEST_TOOL"."CHANGE_VENDOR_SELECTION" ADD FOREIGN KEY ( "SUPPORTING_DOCUMENTATION_ID" ) REFERENCES "MKTG_CART_REQUEST_TOOL"."CHANGE_VENDOR_SUPPORTING_DOCUMENTATION" ("SUPPORTING_DOCUMENTATION_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;