CREATE COLUMN TABLE "MKTG_CART_REQUEST_TOOL".CRT_ISSUE_TYPE
(
	CRT_TYPE_ID BIGINT NOT NULL,
	ISSUE_TYPE_ID BIGINT NOT NULL,
	
	CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE_TZ TIMESTAMP,
	CREATED_USER_ID BIGINT NOT NULL,
	MODIFIED_USER_ID BIGINT,
	ENABLED TINYINT DEFAULT 1, 
	DELETED TINYINT DEFAULT 0
);
ALTER TABLE "MKTG_CART_REQUEST_TOOL"."CRT_ISSUE_TYPE" ADD FOREIGN KEY ( "CRT_TYPE_ID" ) REFERENCES "MKTG_CART_REQUEST_TOOL"."CRT_TYPE" ("CRT_TYPE_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
ALTER TABLE "MKTG_CART_REQUEST_TOOL"."CRT_ISSUE_TYPE" ADD FOREIGN KEY ( "ISSUE_TYPE_ID" ) REFERENCES "MKTG_CART_REQUEST_TOOL"."ISSUE_TYPE" ("ISSUE_TYPE_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;