CREATE COLUMN TABLE "MKTG_CART_REQUEST_TOOL"."VENDOR_DATA_PROTECTION_ANSWER"
(
	 VENDOR_REQUEST_ID BIGINT NOT NULL,
	 QUESTION_ID INTEGER,
	 OPTION_ID INTEGER,
	 CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	 MODIFIED_DATE_TZ TIMESTAMP,
	 CREATED_USER_ID BIGINT NOT NULL,
	 MODIFIED_USER_ID BIGINT,
	 ENABLED TINYINT DEFAULT 1,
	 DELETED TINYINT DEFAULT 0
);

ALTER TABLE "MKTG_CART_REQUEST_TOOL"."VENDOR_DATA_PROTECTION_ANSWER" ADD FOREIGN KEY ( "VENDOR_REQUEST_ID" ) REFERENCES "MKTG_CART_REQUEST_TOOL"."VENDOR_REQUEST" ("VENDOR_REQUEST_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
ALTER TABLE "MKTG_CART_REQUEST_TOOL"."VENDOR_DATA_PROTECTION_ANSWER" ADD FOREIGN KEY ( "QUESTION_ID" ) REFERENCES "MKTG_CART_REQUEST_TOOL"."DATA_PROTECTION_QUESTION" ("QUESTION_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
ALTER TABLE "MKTG_CART_REQUEST_TOOL"."VENDOR_DATA_PROTECTION_ANSWER" ADD FOREIGN KEY ( "OPTION_ID" ) REFERENCES "MKTG_CART_REQUEST_TOOL"."DATA_PROTECTION_OPTION" ("OPTION_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;